// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irobxpqdcqiufshlptft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlyb2J4cHFkY3FpdWZzaGxwdGZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MzIzMTQsImV4cCI6MjA2ODQwODMxNH0.nrBYWYdTtuFuc2cmQEi8Pl_hzt5YDSwNbXP7csq4y5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});