// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbepoxyfxeoycgtwlwkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiZXBveHlmeGVveWNndHdsd2tkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTA3NTEsImV4cCI6MjA2MjM2Njc1MX0.snJBM8gI8uN2g1RvA0vzRvIHJWz108c9KgQuwZ6IwNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});